[package]
name = "rehoboam"
version = "0.1.0"
edition = "2021"
exclude = ["index.node"]

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0"
image = "0.25"
md5 = "0.7"
ndarray = "0.15"
tokenizers = "0.15"
imageproc = "0.24"
whisper-rs = "0.11"
hound = "3.5"
napi = { version = "2", features = ["async", "anyhow", "tokio_rt"] }
napi-derive = "2"
itertools = "0.12.1"
tokio = "1.37.0"
lazy_rc = "0.1.3"

[dependencies.ort]
version = "2.0.0-rc.1"
features = ["load-dynamic", "cuda", "tensorrt"]

[build-dependencies]
napi-build = "2"
