[package]
name = "rehoboam"
version = "0.1.0"
edition = "2021"
exclude = ["index.node"]

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0.82"
image = "0.25.1"
itertools = "0.12.1"
lazy_static = "1.4.0"
ndarray = "0.15.6"
tokenizers = { version = "0.19.1", features = ["hf-hub", "http"] }
napi = { version = "2", features = ["async", "anyhow", "tokio_rt"] }
napi-derive = "2"
hf-hub = "0.3.2"
tokio = "1.37.0"
serde_json = "1.0.116"
uluru = "3.1.0"

[dependencies.ort]
version = "2.0.0-rc.1"
features = ["load-dynamic", "cuda", "tensorrt"]

[build-dependencies]
napi-build = "2"

[dev-dependencies]
comfy-table = "7.1.1"
