/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export type SigLIP = SigLip
export declare class SigLip {
  constructor(quantized: boolean)
  batchEncodeImages(imagePaths: Array<string>): Promise<Array<Array<number>>>
  batchEncodeTexts(texts: Array<string>, cacheResult: boolean): Promise<Array<Array<number>>>
}
