[package]
name = "vidhash"
version = "0.1.0"
edition = "2021"
exclude = ["index.node"]

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0.70"
clap = { version = "4.1.14", features = ["derive"] }
image = "0.24.6"
image_hasher = "1.1.2"
napi = { version = "2", features = ["async"] }
napi-derive = "2"

[build-dependencies]
napi-build = "2"
