# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: solomon.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import core_pb2 as core__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rsolomon.proto\x12\x18me.sylver.marver.solomon\x1a\ncore.proto\"\'\n\x12\x44\x65tectFacesRequest\x12\x11\n\tfile_path\x18\x01 \x01(\t\">\n\x10\x44\x65tectFacesReply\x12*\n\x05\x66\x61\x63\x65s\x18\x01 \x03(\x0b\x32\x1b.me.sylver.marver.core.Face\"\"\n\rGetOCRRequest\x12\x11\n\tfile_path\x18\x01 \x01(\t\":\n\x0bGetOCRReply\x12+\n\x07results\x18\x01 \x03(\x0b\x32\x1a.me.sylver.marver.core.OCR2\xd7\x01\n\x0eSolomonService\x12i\n\x0b\x44\x65tectFaces\x12,.me.sylver.marver.solomon.DetectFacesRequest\x1a*.me.sylver.marver.solomon.DetectFacesReply\"\x00\x12Z\n\x06GetOCR\x12\'.me.sylver.marver.solomon.GetOCRRequest\x1a%.me.sylver.marver.solomon.GetOCRReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'solomon_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_DETECTFACESREQUEST']._serialized_start=55
  _globals['_DETECTFACESREQUEST']._serialized_end=94
  _globals['_DETECTFACESREPLY']._serialized_start=96
  _globals['_DETECTFACESREPLY']._serialized_end=158
  _globals['_GETOCRREQUEST']._serialized_start=160
  _globals['_GETOCRREQUEST']._serialized_end=194
  _globals['_GETOCRREPLY']._serialized_start=196
  _globals['_GETOCRREPLY']._serialized_end=254
  _globals['_SOLOMONSERVICE']._serialized_start=257
  _globals['_SOLOMONSERVICE']._serialized_end=472
# @@protoc_insertion_point(module_scope)
