export enum TaskType {
  FileComputeHashes,
  ImageGenerateThumbhash,
  ImageExtractMetadata,
  ImageGenerateClipVectors,
  ImageExtractExif,
  ImageGeneratePerceptualHash,
  VideoGenerateSubtitles,
  VideoExtractMetadata,
  VideoExtractScreenshots,
  VideoPickThumbnail,
  VideoPickPoster,
  VideoGenerateClipVector,
  VideoGenerateTimeline,
  VideoGenerateThumbhash,
  ImageDetectFaces,
  ImageExtractText,
}
