# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sentry.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0csentry.proto\x12\x17me.sylver.marver.sentry\"F\n\x10GetVectorRequest\x12\x13\n\tfile_path\x18\x04 \x01(\tH\x00\x12\x14\n\ntext_input\x18\x05 \x01(\tH\x00\x42\x07\n\x05input\"D\n\x11GetVectorResponse\x12/\n\x06vector\x18\x01 \x01(\x0b\x32\x1f.me.sylver.marver.sentry.Vector\"\x17\n\x06Vector\x12\r\n\x05value\x18\x01 \x03(\x02\x32u\n\rSentryService\x12\x64\n\tGetVector\x12).me.sylver.marver.sentry.GetVectorRequest\x1a*.me.sylver.marver.sentry.GetVectorResponse\"\x00\x62\x06proto3')



_GETVECTORREQUEST = DESCRIPTOR.message_types_by_name['GetVectorRequest']
_GETVECTORRESPONSE = DESCRIPTOR.message_types_by_name['GetVectorResponse']
_VECTOR = DESCRIPTOR.message_types_by_name['Vector']
GetVectorRequest = _reflection.GeneratedProtocolMessageType('GetVectorRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETVECTORREQUEST,
  '__module__' : 'sentry_pb2'
  # @@protoc_insertion_point(class_scope:me.sylver.marver.sentry.GetVectorRequest)
  })
_sym_db.RegisterMessage(GetVectorRequest)

GetVectorResponse = _reflection.GeneratedProtocolMessageType('GetVectorResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETVECTORRESPONSE,
  '__module__' : 'sentry_pb2'
  # @@protoc_insertion_point(class_scope:me.sylver.marver.sentry.GetVectorResponse)
  })
_sym_db.RegisterMessage(GetVectorResponse)

Vector = _reflection.GeneratedProtocolMessageType('Vector', (_message.Message,), {
  'DESCRIPTOR' : _VECTOR,
  '__module__' : 'sentry_pb2'
  # @@protoc_insertion_point(class_scope:me.sylver.marver.sentry.Vector)
  })
_sym_db.RegisterMessage(Vector)

_SENTRYSERVICE = DESCRIPTOR.services_by_name['SentryService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GETVECTORREQUEST._serialized_start=41
  _GETVECTORREQUEST._serialized_end=111
  _GETVECTORRESPONSE._serialized_start=113
  _GETVECTORRESPONSE._serialized_end=181
  _VECTOR._serialized_start=183
  _VECTOR._serialized_end=206
  _SENTRYSERVICE._serialized_start=208
  _SENTRYSERVICE._serialized_end=325
# @@protoc_insertion_point(module_scope)
