[package]
name = "squtil"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = "1.4.0"
prost = "0.11.9"
sqlite-loadable = "0.0.5"
tonic = "0.10.2"

[lib]
crate-type = ["lib", "cdylib", "staticlib"]

[build-dependencies]
prost-build = { version = "0.11.9" }
